(function(pl) {
	
	var DB_TYPE_NIL = "";
	var DB_TYPE_MYSQL = "MYSQL";
	var DB_TYPE_POSTGRES = "POSTGRES";
	var DB_TYPE_SQLITE3 = "SQLITE3";
	
	pl.extend(pl, {
		
		DB_TYPE_NIL: DB_TYPE_NIL,
		DB_TYPE_MYSQL: DB_TYPE_MYSQL,
		DB_TYPE_POSTGRES: DB_TYPE_POSTGRES,
		DB_TYPE_SQLITE3: DB_TYPE_SQLITE3,
		
		DB_TYPES: [DB_TYPE_MYSQL, DB_TYPE_POSTGRES, DB_TYPE_SQLITE3]
	});
})(pl||{});